### ISSUE TITLE
测试数据文件应该放在哪？

### ISSUE THREAD

**Issue by kevinMintnick** [m969130721/Judge#2]

**Comment by ChinaWim** [comment]
在yml文件 file.server.testcase 配置测试样例目录root路径，每个题目以题目id作为一个目录，输入输出文件分别为input和output作为一个目录。
例如：
root，/home/ming/gkuoj/file/testcase
testcase1 in，/home/ming/gkuoj/file/testcase/1000/input/1.in
testcase1 out，/home/ming/gkuoj/file/testcase/1000/output/1.out
